env: {TERM: xterm-256color}
cursor: {unfocused_hollow: true}
key_bindings:
- {key: V, action: Paste, mods: Control|Shift}
- {key: C, action: Copy, mods: Control|Shift}
- {key: Insert, action: PasteSelection, mods: Shift}
- {key: Key0, action: ResetFontSize, mods: Control}
- {key: Equals, action: IncreaseFontSize, mods: Control}
- {key: Plus, action: IncreaseFontSize, mods: Control}
- {key: Minus, action: DecreaseFontSize, mods: Control}
bell: {duration: 50, color: '#ffffff', animation: EaseOutExpo}
colors:
  bright: {yellow: '#ffa000', cyan: '#26a69a', green: '#9ccc65', magenta: '#ad1457',
    blue: '#81d4fa', white: '#eceff1', black: '#37474f', red: '#ffa74d'}
  normal: {yellow: '#ffc107', cyan: '#009688', green: '#8bc34a', magenta: '#e91e63',
    blue: '#03a9f4', white: '#cfd8dc', black: '#263238', red: '#ff9800'}
  primary: {foreground: '#eceff1', background: '#263238'}
window:
  history: 0
  scrolling: null
  padding: {y: 10, x: 10}
alt_send_esc: true
font:
  normal: {style: Regular, family: Fira Mono}
  offset: {y: 0, x: 0}
  size: 10.5
live_config_reload: true
