env: {TERM: xterm-256color}
cursor: {unfocused_hollow: true, text: CellBackground, cursor: CellForeground}
key_bindings:
- {key: V, action: Paste, mods: Control|Shift}
- {key: C, action: Copy, mods: Control|Shift}
- {key: Insert, action: PasteSelection, mods: Shift}
- {key: Key0, action: ResetFontSize, mods: Control}
- {key: Equals, action: IncreaseFontSize, mods: Control}
- {key: Plus, action: IncreaseFontSize, mods: Control}
- {key: Minus, action: DecreaseFontSize, mods: Control}
bell: {duration: 50, color: '#ffffff', animation: EaseOutExpo}
colors:
  bright: {yellow: '#dede38', green: '#45bf45', cyan: '#2aa7c1', magenta: '#b544ee',
    blue: '#5273f5', black: '#555555', white: '#d0d0d0', red: '#ff4060'}
  normal: {yellow: '#c3c322', green: '#29a329', cyan: '#1999b3', magenta: '#ad2bee',
    blue: '#3d62f5', black: '#000000', white: '#adadad', red: '#e6193c'}
  primary: {foreground: '#adadad', background: '#000000'}
window:
  history: 0
  scrolling: null
  padding: {y: 10, x: 10}
alt_send_esc: true
font:
  normal: {style: Regular, family: Fira Mono}
  size: 10.5
  offset: {y: 0, x: 0}
live_config_reload: true
