env: {TERM: xterm-256color}
cursor: {unfocused_hollow: true}
key_bindings:
- {key: V, action: Paste, mods: Control|Shift}
- {key: C, action: Copy, mods: Control|Shift}
- {key: Insert, action: PasteSelection, mods: Shift}
- {key: Key0, action: ResetFontSize, mods: Control}
- {key: Equals, action: IncreaseFontSize, mods: Control}
- {key: Plus, action: IncreaseFontSize, mods: Control}
- {key: Minus, action: DecreaseFontSize, mods: Control}
bell: {duration: 50, color: '#ffffff', animation: EaseOutExpo}
colors:
  bright: {yellow: '#c1c1c1', cyan: '#eaeaea', green: '#c6c6c6', magenta: '#e2e2e2',
    blue: '#d7d7d7', white: '#ffffff', black: '#aaaaaa', red: '#9d9d9d'}
  normal: {yellow: '#a7a7a7', cyan: '#dfdfdf', green: '#9c9c9c', magenta: '#c6c6c6',
    blue: '#c0c0c0', white: '#ededed', black: '#000000', red: '#787878'}
  primary: {foreground: '#d8d8d8', background: '#000000'}
window:
  history: 0
  scrolling: null
  padding: {y: 10, x: 10}
alt_send_esc: true
font:
  normal: {style: Regular, family: Fira Mono}
  offset: {y: 0, x: 0}
  size: 10.5
live_config_reload: true
