#!/bin/sh

set -e

export XDG_CONFIG_HOME=$HOME/.config
mux="tmux -f $XDG_CONFIG_HOME/tmux.d/tmux.conf"
if $mux has-session -t $1 2>/dev/null; then
    switch_or_attach $1
    exit
fi

$mux new-session -d -s $1 -c '$HOME'
switch_or_attach $1
exit 0
