#!/usr/bin/env zsh

function cd() {
    if ls --color >/dev/null 2>&1; then # GNU `ls`
        colorflag="--color=auto"
    else # OS X `ls`
        colorflag="-G"
    fi
    if [[ "$INSIDE_EMACS" ]]; then
        colorflag=""
    fi
    if [[ -f $VIRTUAL_ENV/.project && -n "$(< $VIRTUAL_ENV/.project 2>/dev/null)" && -z "$@" ]]; then
        # With no args and in a python virtualenv, cd to venv root and ls
        builtin cd $(< $VIRTUAL_ENV/.project) && ls -F ${colorflag}
    elif [[ -n "$(git rev-parse --show-toplevel 2>/dev/null)" && "$(pwd)" == "$(git rev-parse --show-toplevel 2>/dev/null)" && -z "$@" ]]; then
        # With no args and in the root of a git repo, cd to $HOME and ls
        builtin cd $HOME && ls -F ${colorflag}
    elif [[ -n "$(git rev-parse --show-toplevel 2>/dev/null)" && -z "$@" ]]; then
        # With no args and in a git repo, but not at root directory, cd to root of git repo
        builtin cd $(git rev-parse --show-toplevel) && ls -F ${colorflag}
    else
        # In all other cases cd to target directory and ls
        builtin cd $@ && ls -F ${colorflag}
    fi
}
