#!/usr/bin/env zsh
function ereb() {
    if [[ -n $( grep -l '<<< HEAD' $(git ls-files) | sort | uniq ) ]]; then
        emacsclient -c $( grep -l '<<< HEAD' $(git ls-files) | sort -u )
    else
        echo "\n\nno unresolved conflicts"
    fi
}
