#!/usr/bin/env zsh

function home-manager () {
    conf="$(builtin cd $HOME/Documents/dots && git rev-parse --show-toplevel )"
    [[ $(command -v nixos-rebuild) ]] && export _HOME_FLAKE="$conf/#"$HOST
    echo $_HOME_FLAKE
    case "$1" in
        "switch" )
            if [[ ! $(command -v nixos-rebuild) ]]; then
                command home-manager switch --impure --flake $_HOME_FLAKE
                home-manager expire-generations "-14 days"
                return
            else
                command home-manager switch --impure --flake $_HOME_FLAKE
                home-manager expire-generations "-14 days"
                return
            fi
            ;;
        * )
            command home-manager $@ --flake $_HOME_FLAKE
            return
            ;;
    esac
}
