#!/usr/bin/env zsh

function nix-switch() {
    # git 2.35.3 has a bug that prevents flakes from updating, something
    # with diff --no-index. To avoid this, copy nix config to temp directory
    # and build from outside git repo
    tmp=$(mktemp -d)
    print -v thing -P %x
    conf="$(builtin cd ${thing/nix-switch/} && git rev-parse --show-toplevel )"
    command cp -r $conf/nixos $tmp
    sudo nixos-rebuild switch --flake "$tmp/nixos/#"
}
