#!/usr/bin/env zsh

function update() {

    if [[ $(command -v home-manager) ]]; then
        home-manager expire-generations "-14 days"
    fi
    if [[ $(command -v nixos-rebuild) ]] ; then
        # Git/nix are fixed, but committing the flake.lock is not
        # something I'm interested in.
        (
            conf="$(builtin cd $HOME/Documents/dots && git rev-parse --show-toplevel )"
            cd $conf || return
            git checkout flake.lock
            git pull
            nix flake update --commit-lock-file
            sudo nixos-rebuild boot --impure --flake "$conf/#"  --upgrade-all
            # && \
            # sudo nix-collect-garbage -d --delete-older-than 14d && \
            # sudo nix store optimise
        )
        # nix-collect-garbage -d --delete-older-than 14d
    elif [[ $(command -v yay) ]]; then
        yay -Syu --noconfirm --sudoloop
        orphans
        echo '' > /tmp/updates
    elif [[ $(command -v pacman) ]]; then
        pacman -Syu --noconfirm
        orphans
        echo '' > /tmp/updates
    elif [[ $(command -v apt) ]]; then
        sudo apt update && sudo apt full-upgrade -y
    elif [[ $(command -v zypper) ]]; then
        sudo zypper refresh
        sudo zypper dup
    elif [[ $(command -v freebsd-update) ]]; then
        sudo freebsd-update fetch
        sudo freebsd-update install
        sudo pkg update
        sudo pkg upgrade
    fi

    if [[ $(command -v home-manager) ]] ; then
        home-manager switch
        nix-collect-garbage -d --delete-older-than 14d
        nix store optimise
    fi
    if [[ $(command -v flatpak) ]] && [[ -z $SSH_CLIENT ]] ; then
        echo "\n flatpak \n"
        flatpak update -y
    fi
    xmonad --recompile
    gup
    bell
}
