#!/usr/bin/env zsh
function updatemailcert() {
openssl s_client -connect vps68417.inmotionhosting.com:995 -showcerts 2>&1 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sed -ne '1,/-END CERTIFICATE-/p' > ~/.config/certs/gilsons.org.pem

}
