#!/usr/bin/env zsh

function update() {
    sudo -v
    gup
    if [[ $(command -v nixos-rebuild) ]] ; then
        # git 2.35.3 has a bug that prevents flakes from updating, something
        # with diff --no-index. To avoid this, copy nix config to temp directory
        # and build from outside git repo
        (
        print -v thing -P %x
        tmp=$(mktemp -d)
        conf="$(builtin cd  ${thing/update/} && git --work-tree=${thing/update/} rev-parse --show-toplevel )"
        command cp -r "$conf/nixos/" $tmp
        sudo nixos-rebuild boot --flake "$tmp/nixos/#"  --upgrade-all
        )
        return
        nix-collect-garbage -d --delete-older-than 14d
        nix store optimise
    elif [[ $(command -v yay) ]]; then
        yay -Syu --noconfirm --sudoloop
        xmonad --recompile
        orphans
        echo '' > /tmp/updates
    elif [[ $(command -v pacman) ]]; then
        pacman -Syu --noconfirm
        xmonad --recompile
        orphans
        echo '' > /tmp/updates
    elif [[ $(command -v apt) ]]; then
        sudo apt update
        sudo apt upgrade
    elif [[ $(command -v zypper) ]]; then
        sudo zypper refresh
        sudo zypper dup
    elif [[ $(command -v freebsd-update) ]]; then
        sudo freebsd-update fetch
        sudo freebsd-update install
        sudo pkg update
        sudo pkg upgrade
    fi

    if [[ $(command -v flatpak) ]] && [[ -z $SSH_CLIENT ]] ; then
        echo "\n flatpak \n"
        flatpak update -y
    fi
    bell
}
