#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --show-toplevel)"
trap 'rm -f "$dir/.tags"' EXIT
trap 'rm -f "$dir/../.tags"' EXIT
trap 'rm -f "$dir/.etags"' EXIT
trap 'rm -f "$dir/../.etags"' EXIT

ctags -R --tag-relative -L - -f"$dir/.tags" ./


ctags -R -e --tag-relative -L - -f"$dir/.etags" ./
