#!/bin/sh
.git/hooks/ctags >/dev/null 2>&1 &

base=$(git rev-parse --show-toplevel)
while read -r f
do
    gpg -d --quiet "$base/$f.gpg" > "/tmp/$(basename "$f" )"
done < "$base/config/crypt"

git submodule foreach 'git checkout -f master'
git submodule foreach 'git submodule update --recursive --init'
exit 0
