#!/bin/sh
base=$(git rev-parse --show-toplevel)
while read -r f
do
    if ! test -f "$base/$f.gpg"; then
        # echo 'make file'
        gpg -r jonathandavis@gilsons.org --encrypt "$base/$f"
    fi
    if git status | grep -q "$f"; then
        gpg -d --quiet "$base/$f.gpg" > "/tmp/$(basename "$f" )"
        if  /usr/bin/diff -q "$base/$f" "/tmp/$(basename "$f" )"; then
            rm "/tmp/$(basename "$f" )"
            exit 0
        else
            echo encrypt
            rm "$base/$f.gpg"
            gpg -r jonathandavis@gilsons.org --encrypt "$base/$f"
            git rm --cached "$base/$f"
            rm "/tmp/$(basename "$f" )"
            exit 0
        fi
    fi
    if test -f "/tmp/$f"; then
        rm "/tmp/$(basename "$f" )"
    fi
done < "$base/config/crypt"
