"{{{ defaults
if filereadable(expand('$VIMRUNTIME/defaults.vim'))
    unlet! g:skip_defaults_vim
    source $VIMRUNTIME/defaults.vim
endif

" Enable file type detection and do language-dependent indenting.
filetype plugin indent on

" Switch syntax highlighting on
syntax on
"}}}
"{{{ colors
colorscheme portable
"}}}
"{{{ Plugin loading and settings
let g:VimPack_Setup_Folders = ['after', 'autoload', 'backup', 'colors', 'doc', 'spell', 'swaps', 'syntax','plugin', 'undo']
let g:VimPack_Auto_Install = 1
let g:VimPack_Auto_Update = 1

call pack#load()

PlugOpt 'dzeban/vim-log-syntax'
PlugOpt 'w0rp/ale'
if executable('fzf')
    if isdirectory('/usr/local/opt/fzf')
        set runtimepath+=/usr/local/opt/fzf
    endif
    PlugStart 'junegunn/fzf.vim'
endif
PlugStart 'bronson/vim-visual-star-search'
PlugStart 'editorconfig/editorconfig-vim'
PlugStart 'git@gitlab.com:yramagicman/auto-omnicomplete'
PlugStart 'hail2u/vim-css3-syntax'
PlugStart 'jwalton512/vim-blade'
PlugStart 'leafgarland/typescript-vim'
PlugStart 'othree/html5.vim'
PlugStart 'posva/vim-vue'
PlugStart 'tpope/vim-commentary'
PlugStart 'tpope/vim-repeat'
PlugStart 'tpope/vim-surround'
PlugStart 'cakebaker/scss-syntax.vim'
PlugStart 'vim-scripts/vim-indent-object'
packadd! matchit
if ! has('nvim')
    packadd! editexisting
endif
let g:AutoOmniComplete_tab = 1
"}}}
"{{{ autocommands for loading extensions
augroup extensions
    autocmd!
    autocmd FileType vim,css,scss,sass,html,javascript,python,php,c,cpp,typescript,zsh,sh silent! packadd ale | redraw
    autocmd BufRead *.org  set filetype=org
    autocmd FileType vue syn sync fromstart
augroup end
"}}}
"{{{ ale settings
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
"}}}
let mapleader=","
let g:NoAutoPairs = 1

" expand( '%:e') extension
" expand( '%:h') filename
" expand( '%:p') real path
" expand( '%:t') directory
" expand( '%:S') path as string
