#!/bin/sh


export PATH="/run/current-system/sw/bin/:$PATH"
nix flake update "/home/jonathan/Documents/dots/#" > /dev/shm/pc-flake  2>&1
nix flake update "/home/jonathan/Documents/dots/nixos/browncoat/#" > /dev/shm/server-flake  2>&1
