#!/bin/sh

export PATH="/etc/profiles/per-user/jonathan/bin/:/run/current-system/sw/bin/:$PATH"
[ -n "$(grep -v 'warning: Git tree' /dev/shm/pc-flake)" ] && notify-send "Update available"
# notify-send "$(cat /dev/shm/server-flake)"
# rm /dev/shm/server-flake
