command! -nargs=1 GCommitM call git#CommitM('<args>')
command! -nargs=0 GCommit call git#Commit()
command! -nargs=1 GLog call git#Log('<args>')
command! -nargs=1 GLogVerbose call git#Logv('<args>')
command! -nargs=0 GStatus call git#Status()
command! -nargs=0 GPush call git#Push()
command! -nargs=0 GAddB call git#AddBuffer()
command! -nargs=0 GAddAll call git#AddAll()
