command! -nargs=1 GCommit call git#Commit('<args>')
command! -nargs=1 GLog call git#Log('<args>')
command! -nargs=1 GLogVerbose call git#Logv('<args>')
command! -nargs=0 GStatus call git#Status()
command! -nargs=0 GAddB call git#AddBuffer()
