#!/bin/sh

set -e

if tmux has-session -t $(hostname | cut -d '.' -f 1) 2>/dev/null; then
    $HOME/bin/switch_or_attach $(hostname | cut -d '.' -f 1)
    exit
fi

tmux new-session -d -s $(hostname | cut -d '.' -f 1) -c '$HOME'
$HOME/bin/switch_or_attach $(hostname | cut -d '.' -f 1)
exit 0
