#!/bin/sh

set -e

if tmux has-session -t $(hostname) 2>/dev/null; then
    $HOME/bin/switch_or_attach $(hostname)
    exit
fi

tmux new-session -d -s $(hostname) -c '$HOME' -n emacs
tmux send-keys -t $(hostname):emacs 'emacs $HOME' Enter
tmux new-window -t $(hostname)
tHOME/bin/switch_or_attach $(hostname)
exit 0
