#!/usr/bin/env bash

hyprctl activewindow | awk '/^\s*title:/ {$1=""; print $0 }'
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
hyprctl activewindow | awk '/^\s*title:/ {$1=""; print $0 }'
done
