#!/usr/bin/env bash

spaces (){
    WORKSPACE_WINDOWS=$(hyprctl workspaces | awk '/ID/ { print $3 }' | sort -n )
    ACTIVE_SPACE=$( hyprctl monitors | awk '/active/ { print $3 }')
    WINDOW_COUNT=$(hyprctl workspaces | grep -A 2 "workspace ID $ACTIVE_SPACE" | awk '/windows/ {print $2}')
    # echo $ACTIVE_SPACE
    echo " -- $WINDOW_COUNT $( echo $WORKSPACE_WINDOWS | sed "s/$ACTIVE_SPACE/[&]/" )"
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    spaces
done
