#!/bin/sh

set -e
export XDG_CONFIG_HOME=$HOME/.config
mux="tmux -f $XDG_CONFIG_HOME/tmux.d/tmux.conf"
if $mux has-session -t django 2> /dev/null; then
  $HOME/bin/switch_or_attach django
  exit
fi

$mux new-session -d -s django -n ranger
$mux send-keys -t django:ranger "workon tbs-django" Enter
$mux send-keys -t django:ranger "ranger ." Enter

$mux new-window -t django -n http
$mux send-keys -t django:http "workon tbs-django" Enter
$mux send-keys -t django:http "manage.py runserver" Enter
$mux split-window -h -t django:http
$mux send-keys -t django:http.right "workon tbs-django" Enter
$mux send-keys -t django:http.right "manage.py shell" Enter

$mux new-window -t django -n compass
$mux send-keys -t django:compass "workon tbs-django" Enter
$mux send-keys -t django:compass "cd /home/jonathan/Sites/tbs_django/best_schools/static" Enter
$mux send-keys -t django:compass "compass watch" Enter

$mux new-window -t django -n shell
$mux send-keys -t django:shell "workon tbs-django" Enter
$mux send-keys -t django:shell "nohup google-chrome-beta --incognito http://127.0.0.1:8000 &" Enter
$mux send-keys -t django:shell "nohup google-chrome-beta --incognito http://127.0.0.1:8000/admin &" Enter
$mux send-keys -t django:shell "clear" Enter
$HOME/bin/switch_or_attach django:1
exit 0
