#!/bin/sh

set -e

export XDG_CONFIG_HOME=$HOME/.config
mux="tmux -f $XDG_CONFIG_HOME/tmux.d/tmux.conf"
if $mux has-session -t iweb 2> /dev/null; then
  switch_or_attach iweb
  exit
fi

$mux new-session -d -s iweb -n front-end

$mux send-keys -t iweb:front-end "cd ~/Sites/iwebvisit" Enter
$mux send-keys -t iweb:front-end "$EDITOR . " Enter
$mux new-window -t iweb -n back-end
$mux send-keys -t iweb:back-end "cd ~/Sites/iwebvisit-api" Enter
$mux send-keys -t iweb:back-end  "$EDITOR . " Enter
$mux new-window -t iweb -n admin
$mux send-keys -t iweb:admin "cd ~/Sites/iwebvisit-admin" Enter
$mux send-keys -t iweb:admin  "$EDITOR . " Enter
$mux new-window -t iweb -n server
$mux split-window -h -t iweb:server
$mux send-keys -t iweb:server.left "cd ~/Sites/iwebvisit-api" Enter
$mux send-keys -t iweb:server.right "cd ~/Sites/iwebvisit" Enter
$mux send-keys -t iweb:server.left "php artisan serve" Enter
$mux send-keys -t iweb:server.right "npm start" Enter
switch_or_attach iweb:front-end.left
exit 0
