#!/bin/sh

set -e
export XDG_CONFIG_HOME=$HOME/.config
mux="tmux -f $XDG_CONFIG_HOME/tmux.d/tmux.conf"
if test "$1" = ''; then
    echo "please provide one of the following as an argument:"
    find ~/Sites -maxdepth 2 -type f  -name 'artisan'| cut -d '/' -f 5 | sort
    exit
fi

if $mux has-session -t "$1" 2> /dev/null; then
  "switch_or_attach" "$1"
  exit
fi

$mux new-session -c "$HOME/Sites/$1" -d -s "$1" -n dev
$mux send-keys -t "$1":dev "cd $HOME/Sites/$1" Enter
$mux send-keys -t "$1":dev "$EDITOR $HOME/Sites/$1 " Enter

$mux new-window -t "$1" -c "$HOME/Sites/$1" -n shell

$mux new-window -t "$1" -c "$HOME/Sites/$1" -n server
$mux split-window -c "$HOME/Sites/$1" -h -t "$1":server
$mux send-keys -t "$1":server.left "php artisan serve" Enter
$mux send-keys -t  "$1":server.right "npm run watch" Enter

"switch_or_attach" "$1":shell.left
exit 0
