#!/bin/sh

set -e
export XDG_CONFIG_HOME=$HOME/.config
mux="tmux -f $XDG_CONFIG_HOME/tmux.d/tmux.conf"
if test "$1" = ''; then
    echo "please provide one of the following as an argument:"
    find ~/Sites -maxdepth 2 -type d  -name 'wp-content'| cut -d '/' -f 5 | sort
    exit
fi

if $mux has-session -t $1 2> /dev/null; then
  switch_or_attach $1
  exit
fi

if [[ -z $(pgrep httpd) && -z $(pgrep mysqld) ]] ; then
    server-up
fi
$mux new-session -c "$HOME/Sites/" -d -s $1 -n dev
$mux send-keys -t $1:dev "cd $HOME/Sites/$1/wp-content/themes" Enter
$mux send-keys -t $1:dev "emacsclient $HOME/Sites/$1/wp-content/themes & disown" Enter

$mux new-window -t $1 -c "$HOME/Sites" -n shell


$mux new-window -t $1 -c "$HOME/Sites" -n hangups
$mux send-keys -t $1:hangups "$HOME/Sites/hangups/bin/hangups" Enter

$mux new-window -t $1 -c "$HOME/Sites/" -n sass
$mux send-keys -t $1:sass "cd $HOME/Sites/$1/wp-content/themes" Enter

$mux new-window -t $1 -c "$HOME/Sites" -n chrome
$mux send-keys -t $1:chrome "nohup google-chrome-beta --incognito http://tbs.local &" Enter
$mux send-keys -t $1:chrome "nohup google-chrome-beta --incognito http://tbs.local/wp-admin &" Enter
$mux send-keys -t $1:chrome "exit" Enter
switch_or_attach $1:shell.left
exit 0
