#!/bin/sh
hour="/home/.snapshots/$(date -Ihour)"
day="/home/.snapshots/$(date -I)"
bfs="/run/current-system/sw/bin/btrfs"
[[ -d $hour ]] || $bfs subvolume snapshot -r -- "/home" $hour
[[ -d $day ]] || $bfs subvolume snapshot -r -- "/home" $day

for hourly in /home/.snapshots/"$(date -I -d 'yesterday')T"*; do
    [[ -d $hourly ]] && $bfs subvolume delete $hourly >> /home/jonathan/remove
done
