#!/bin/sh
set -eo pipefail
export PATH="/run/current-system/sw/bin/:/run/wrappers/bin/"
[[ -d /var/cache/backup ]] || mkdir -p /var/cache/backup
day="/home/.snapshots/$(date -I)"
stateFile="/var/cache/backup/state"

[[ -f $stateFile ]] || echo 0 > $stateFile
last="$(cat $stateFile)"
[[ "$day" != "$last" ]] && echo "Backing up /home from snapshot $last"

ping -c 3 -q 100.94.223.34
if [[ "$day" != "$last" ]] && [[ $? ]]; then
    if [[ -d $last ]]; then
    btrfs send -c $last $day | \
        ssh jonathan@100.94.223.34 "sudo /opt/receive-backup $(hostname)" && \
        echo $day > $stateFile
    else
    btrfs send $day | \
        ssh jonathan@100.94.223.34 "sudo /opt/receive-backup $(hostname)" && \
        echo $day > $stateFile
    fi
fi
