#!/bin/sh

userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if test "$( hostname )" == 'artoo'; then
    echo 'Xft.dpi: 192' | xrdb -override
fi
# start some nice programs

# if [ -d /etc/X11/xinit/xinitrc.d ] ; then
#  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#   [ -x "$f" ] && . "$f"
#  done
#  unset f
# fi


if command -v alacritty  > /dev/null 2>&1 ; then
    export TERMINAL=alacritty
elif command -v st > /dev/null; then
    export TERMINAL=st
elif command -v urxvt-256color > /dev/null; then
    export TERMINAL=urxvt-256color
elif command -v urxvt > /dev/null; then
    export TERMINAL=urxvt
elif command -v uxterm > /dev/null; then
    export TERMINAL=uxterm
else
    export TERMINAL=xterm
fi

( "$HOME/.config/screenlayout/default.sh" ) &

# exec "$HOME/.config/dwm/autostart.sh" &
# exec "$HOME/bin/statusline" &
# exec "$HOME/bin/dwmrestart"
exec awesome
